
const product_card=[
    {
        id:1,
        name:'Naruto',
        type:'Ninjutsu',
        rating:5,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/naruto.jpeg",
        url:" https://jsonkeeper.com/b/8LI1"
        
    },
    {
        id:2,
        name:'Sasuke',
        type:'Ninjutsu',
        rating:5,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/sasuke.jpeg",
        url:"https://jsonkeeper.com/b/ODZL"
    },
    {
        id:3,
        name:'Sakura',
        type:'Medic',
        rating:2,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/sakura.jpeg",
        url:"https://jsonkeeper.com/b/IHOV"
    },
    {
        id:4,
        name:'Kakashi',
        type:'Ninjutsu',
        rating:5,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/kakashi.jpeg",
        url:"https://jsonkeeper.com/b/7JLO"
    },
    {
        id:5,
        name:'Guy',
        type:'Taijutsu',
        rating:5,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/guy.jpeg",
        url:" https://jsonkeeper.com/b/IS8G"
    },
    {
        id:6,
        name:'Rock Lee',
        type:'Taijutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/lee.jpeg",
        url:"https://jsonkeeper.com/b/CKVO"
    },
    {
        id:7,
        name:'Neji',
        type:'Taijutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/neji.jpeg",
        url:"https://jsonkeeper.com/b/IE8V"
    },
    {
        id:8,
        name:'Asuma',
        type:'Ninjutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/asuma.jpeg",
        url:"https://jsonkeeper.com/b/MYFU"
    },
    {
        id:9,
        name:'Shikamaru',
        type:'Ninjutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/shikamaru.jpeg",url:"https://jsonkeeper.com/b/DJXH"
    },
    {
        id:10,
        name:'Choji',
        type:'Ninjutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/choji.jpeg",url:"https://jsonkeeper.com/b/HDHQ"
    },
    {
        id:11,
        name:'Ino',
        type:'Ninjutsu',
        rating:2,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/ino.jpeg",url:"https://jsonkeeper.com/b/0A4U"
    },
    {
        id:12,
        name:'Kurenai',
        type:'Genjutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/kurenai.jpeg",url:"https://jsonkeeper.com/b/R55A"
    },
    {
        id:13,
        name:'Hinata',
        type:'Taijutsu',
        rating:4,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/hinata.jpeg",url:"https://jsonkeeper.com/b/YZ2G"
    },
    {
        id:14,
        name:'Shino',
        type:'Ninjutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/shino.jpeg",url:"https://jsonkeeper.com/b/1MB6"
    },
    {
        id:15,
        name:'Kiba',
        type:'Ninjutsu',
        rating:3,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/kiba.jpeg",url:" https://jsonkeeper.com/b/W8EW"
    },
    {
        id:16,
        name:'Itachi',
        type:'Genjutsu',
        rating:5,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/itachi.jpeg",url:"https://jsonkeeper.com/b/71IH"
    },
    {
        id:17,
        name:'Minato',
        type:'Ninjutsu',
        rating:5,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/minato.jpeg",url:"https://jsonkeeper.com/b/HMKU"
    },
    {
        id:18,
        name:'Obito',
        type:'Ninjutsu',
        rating:4,
        price:0.02,
        currency:'ETH',
        thumb:"https://gateway.pinata.cloud/ipfs/QmdvBJGcvmwVmEWSfXewDk59TmAf3VMsdK2p5Jv8h6jcQY/obito.jpeg",url:"https://jsonkeeper.com/b/NSC0"
    },


]
export default product_card;

